package edu.gmu.cs321;

import java.sql.*; 

public class Petition {

    private int petitionID; // Identification number/code assigned to the petition auto generated by the database
    private int petitionerID; // Identification number/code assigned to the immigrant petitioner
    private String submissionDate; // Date petition was submitted
    private String status; // Current status of the petition
    
    // Constructor for creating a new petition
    public Petition(int petitionerID, String submissionDate, String status) {
        this.petitionerID = petitionerID;
        this.submissionDate = submissionDate;
        this.status = status;
    }

    // Constructor for loading existing petitions (e.g., from DB)
    public Petition(int petitionID, String status) {
        this.petitionID = petitionID;
        this.status = status;
    }

    // function to create a new petition in the database
    // Returns the petitionID of the newly created petition, or 0 if creation failed  
    public int createPetition() {
        String insertQuery = "insert into petition (userID, status) values (?,?)";
        int petitionID = 0;
        try {
            Connection connection = DB_Connection.getConnection();
            PreparedStatement preparedStatement = connection.prepareStatement(insertQuery, Statement.RETURN_GENERATED_KEYS);
            preparedStatement.setInt(1, petitionerID);
            preparedStatement.setString(2, status);
            int rowsAffected = preparedStatement.executeUpdate();
            if (rowsAffected > 0) {
                System.out.println("petition added successfully.");
                ResultSet generatedKeys = preparedStatement.getGeneratedKeys();
                if (generatedKeys.next()) {
                    petitionID = generatedKeys.getInt(1);
                    System.out.println("Generated ID: " + petitionID);
                }
            } else {
                System.out.println("Error adding petition.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return petitionID; // placeholder for TDD
    }

    // function to update a petition in the database
    // Returns true if the petition was updated successfully, false otherwise
    public boolean updatePetitionID(int newPetitionID) {
        this.petitionID = newPetitionID;
        return petitionID != 0; 
    }

    //--------------------------------------------------------------------------------//
    //                                  SETTERS                                       //
    //--------------------------------------------------------------------------------//

    // Updates the petition ID to the new inputted one
    public void setPetitionID(int newPetitionID) { this.petitionID = newPetitionID; }

    // Updates the petitioner ID to the new inputted one
    public void setPetitionerID(int newPetitionerID) { this.petitionerID = newPetitionerID; }

    // Updates petition submission date to the new inputted one
    public void setSubmissionDate(String newSubmissionDate) { this.submissionDate = newSubmissionDate; }

    // Updates petition status to the new inputted one
    public void setStatus(String newStatus) { this.status = newStatus; }



    //--------------------------------------------------------------------------------//
    //                                  GETTERS                                       //
    //--------------------------------------------------------------------------------//

    // Returns the petition ID as a string
    public int getPetitionID() { return petitionID; }

    // Returns the petitioner ID as a string
    public int getPetitionerID() { return petitionerID; }

    // Returns the recorded petition submission date
    public String getSubmissionDate() { return submissionDate; }

    // Returns the status of petition
    public String getStatus() { return status; }
}